### ISSUE TITLE
Conflict version issue

### ISSUE THREAD

**Issue by tundak** [kornrunner/php-secp256k1#3]
Problem 1
    - Installation request for kornrunner/secp256k1 dev-master -> satisfiable by kornrunner/secp256k1[dev-master].
    - Can only install one of: kornrunner/secp256k1[0.1.2, dev-master].
    - Installation request for kornrunner/secp256k1 ^0.1.2 -> satisfiable by kornrunner/secp256k1[0.1.2].

**Comment by kornrunner** [comment]
It seems that some package that you've required is asking for `dev-master` version, and another one is asking for `^0.1.2`. You should check with upstream, that issue cannot be fixed within this package.
