### ISSUE TITLE
Is there anyway to generate wallet address too?

### ISSUE THREAD

**Issue by onlinecheckwriter** [kornrunner/php-secp256k1#4]
Hello,
Is there is any way to generate 
address" => $wallet_address, "private_key" => $wallet_private_key, "pubic_key"

Reference:
https://gist.github.com/irmaster/099758d0266634fe7e830b5ab674b55b

It is not working....

**Comment by kornrunner** [comment]
Please see https://github.com/kornrunner/php-ethereum-address instead.

Also, please note that the output of given library doesn't add `0x` prefix to strings, so you should add it if you need it. Thanks!

**Comment by onlinecheckwriter** [comment]
Thank you very much.
